Update staking v2
kardiachain/go-kardia pull request #112
Opened 2020-12-17 04:20 UTC by duypv1997

- Implement params set contract
- Implement proposal and vote to change max validator
- Remove min self delegation
- Repo staking v2: https://github.com/kardiachain/staking-contract/pull/8

2020-12-17 07:17 UTC, lewtran requested changes

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            inflationMax: 7 * 10**16,
5%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            inflationMin: 189216 * 10**11 // 1,89216%
1%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            inflationRateChange: 2 * 10**16, // 2%
1%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            goalBonded: 35 * 10**16,
50%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            maxValidators: 20
maxProposers

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            minValidatorBalance: 12500000 * 10**18 // 12500000 KAI
minValidatorStake

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            minSignedPerWindow: 5 * 10**16,
50%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            unbondingTime: 1814400,
604800 // 7 days for withdraw

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            slashFractionDoubleSign: 5 * 10**16,
25%

2020-12-17 07:17 UTC, lewtran commented on kvm/smc/dpos/Params.sol
> +            slashFractionDowntime: 1 * 10**14,
5%

2020-12-22 04:41 UTC, lewtran commented
Please update the latest staking source code

2020-12-22 08:16 UTC, lewtran requested changes

2020-12-22 08:16 UTC, lewtran commented on mainchain/api_interface.go
> +			continue
double check this @duypv1997

2020-12-24 07:44 UTC, lewtran requested changes

2020-12-24 07:44 UTC, lewtran commented on mainchain/genesis/genesis.go
>  		}
Re enable this

2020-12-24 07:47 UTC, lewtran commented
https://github.com/kardiachain/go-kardia/blob/Update/staking_v2/kai/state/cstate/store.go#L323 
Implement here to check if the validators start with genesis or not

2020-12-24 07:49 UTC, lewtran commented
Add "StartWithGenesis" flag
https://github.com/kardiachain/go-kardia/blob/Update/staking_v2/cmd/cfg/genesis.yaml#L31

2020-12-24 08:40 UTC, y4t0g4m1 commented on mainchain/genesis/genesis.go
>  		}
Done!

2020-12-26 02:49 UTC, merged