Impl event newHeads
kardiachain/go-kardia pull request #128
Opened 2021-01-07 09:27 UTC by ngdlong91

2021-01-18 03:44 UTC, lewtran commented
Please add descriptions and its purpose

2021-01-19 09:32 UTC, ngdlong91 commented
Add description

2021-01-20 04:57 UTC, lewtran requested changes

2021-01-20 04:57 UTC, lewtran commented on mainchain/kardia_service.go
> +			Public:    true,
Move these lines below 'NewPublicKaiAPI' service

2021-01-20 05:03 UTC, ngdlong91 commented on mainchain/kardia_service.go
> +			Public:    true,
Done

2021-01-20 05:03 UTC, lewtran commented
LGTM

2021-01-20 05:04 UTC, merged