Implement stacktrie to improve RLP/hashing performance
kardiachain/go-kardia pull request #244
Opened 2023-01-05 04:44 UTC by trinhdn97

Following https://github.com/kardiachain/go-kardia/issues/237

- [X] Implement stacktrie
- [X] Use stacktrie for block and transactions hashing instead of trie
- [X] Expose and use the encoder buffer for trie RLP actions

2023-01-05 06:28 UTC, phatngluu commented on types/transaction_test.go
> +	t.Logf(common.ToHex(should))
If this is unintended comment, please remove it.

2023-01-05 07:49 UTC, phatngluu commented on types/block_test.go
> +			err := block.ValidateBasic(nil)
Please pass a stack trie to ValidateBasic, then uncomment two above test cases

2023-01-05 07:53 UTC, phatngluu requested changes
changes

2023-01-06 04:17 UTC, phatngluu approved these changes

2023-01-16 02:34 UTC, thientn approved these changes

2023-02-13 08:10 UTC, merged